name: Binds (Python)

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint, Python
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0

    - name: Check lints
      run: uvx ruff check --output-format=github .

    - name: Check formatting
      run: uvx ruff format --check --diff .

  build:
    name: Build (${{ matrix.name }}), Python
    needs: lint
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include: >-
          ${{ fromJSON(startsWith(github.ref, 'refs/tags/')
          && '[
          {"name": "linux-arm64",   "runs-on": "ubuntu-24.04-arm", "archs": "aarch64"},
          {"name": "linux-amd64",   "runs-on": "ubuntu-latest",    "archs": "x86_64"},
          {"name": "macos-arm64",   "runs-on": "macos-latest",     "archs": "arm64",   "macos-target": "14.0"},
          {"name": "macos-amd64",   "runs-on": "macos-15-intel",   "archs": "x86_64",  "macos-target": "14.0"},
          {"name": "windows-amd64", "runs-on": "windows-latest",   "archs": "AMD64"},
          {"name": "windows-arm64", "runs-on": "windows-11-arm",   "archs": "ARM64"}
          ]'
          || '[
          {"name": "linux-arm64",   "runs-on": "ubuntu-24.04-arm", "archs": "aarch64"},
          {"name": "macos-arm64",   "runs-on": "macos-latest",     "archs": "arm64",   "macos-target": "14.0"},
          {"name": "windows-amd64", "runs-on": "windows-latest",   "archs": "AMD64"}
          ]') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        enable-cache: false

    - name: Build and test wheels
      uses: pypa/cibuildwheel@v4.1.1
      env:
        CIBW_ARCHS: ${{ matrix.archs }}
        MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
