name: Build and test binds

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main') && github.sha || '' }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-go:
    name: Go
    uses: ./.github/workflows/binds-go.yml

  build-js:
    name: JavaScript
    uses: ./.github/workflows/binds-js.yml

  build-rs:
    name: Rust
    uses: ./.github/workflows/binds-rs.yml

  build-py:
    name: Python
    uses: ./.github/workflows/binds-py.yml
